# ---

# - name: Setup the Git repo
#   git: repo={{ git_repo }}
#        version="{{ git_branch }}"
#        dest={{ project_path }}
#        accept_hostkey=yes
#   when: setup_git_repo is defined and setup_git_repo
#   tags: git
#   become: yes
#   become_user: deploy
